### ISSUE TITLE
Node Provider Configuration Issue

### ISSUE THREAD

**Issue by lebensterben** [neovim/node-client#102]
I think there's a bug related to how the neovim interpret the configuration for Node.js provider. Below are the steps to duplicate the problem I had, and the way how I fixed it.
## Problem:
- I have a clean install of node, npm, and nvm, and I installed the node-client globally with `npm install -g neovim`.
- Then I editted the neovim configuration file (under ~/.config/neovim/init.vim on my disk) with `let g:node_host_prog = '~/.nvm/versions/node/v11.3.0/bin/neovim-node-host'`.
- If I run the `:checkhealth` command in neovim, it always shows that the `node '~/.nvm/versions/node/v11.3.0/bin/neovim-node-host'' --version` throws an error which says it cannot find the file `/Users/myusername/~/.nvm/versions/node/v11.3.0/bin/neovim-node-host'`
## My Fix:
- I change the configuration to `let g:node_host_prog = '.nvm/versions/node/v11.3.0/bin/neovim-node-host'` and the `:checkhealth` finally passed with no error.

**Comment by justinmk** [comment]
That looks like a bug in Nvim, not the node-client. And it might only be a bug in `:checkhealth`.

**Comment by justinmk** [comment]
> I change the configuration to `let g:node_host_prog = '.nvm/versions/node/v11.3.0/bin/neovim-node-host'`

Better to use `expand()` instead. Like this:

    let g:node_host_prog = expand('~/.nvm/versions/node/v11.3.0/bin/neovim-node-host')
