### ISSUE TITLE
Where's the rplugin/node directory?

### ISSUE THREAD

**Issue by KsRyY** [neovim/node-client#106]
In README it shows that node plugin should be put into the `rplugin/node` directory, but where's it?
Is it in `~/.local/share/nvim/rplugin/node` or `~/config/nvim/rplugin/node`?

**Comment by justinmk** [comment]
Anywhere on the editor 'runtimepath'. 

With `nvim -u NORC`, `:set rtp?` shows this:

      runtimepath=~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,...

So `~/config/nvim/rplugin/node` will work. But your other suggestion, `~/.local/share/nvim/rplugin/node` will not work: it is missing the `/site` path segment.

**Comment by KsRyY** [comment]
OK thanks

**Comment by KsRyY** [comment]
And what's the runtimepath on Windows?

**Comment by justinmk** [comment]
Use `:set rtp?` to see the runtimepath.

**Comment by KsRyY** [comment]
Thanks
