### ISSUE TITLE
process.stdout.write or console.log in forked process killing the plugin process

### ISSUE THREAD

**Issue by shri3k** [neovim/node-client#107]
So, I've got a very peculiar case where I was noticing that the plugin process dies whenever a forked process tries to call `console.log` or `process.stdout.write`. 

## Steps to reproduce:

```sh
cat << EOF > .vimrc
execute 'set runtimepath+='.getcwd()
EOF

mkdir -p ./rplugin/node/sample.vim

cat << EOF > ./rplugin/node/sample.vim/index.js
const { fork } = require('child_process');

module.exports = plugin => {
  function TestMe() {
    const child = fork(\`\${__dirname}/child.js\`);
    console.log('--end function--');
  }

  plugin.registerCommand("TestMe", [plugin.nvim.buffer, TestMe]);
};

process.on('exit', msg => {
  console.log('exiting..', msg);
})
EOF

cat << EOF > ./rplugin/node/sample.vim/child.js
(function test(){
  console.log("should print hello");
  return "hello";
}());
EOF

cd ./rplugin/node/sample.vim && npm init -y

cd ../../../
nvim -u .vimrc +UpdateRemotePlugin
```

Now when we start nvim
```sh
NVIM_NODE_LOG_FILE=./loggy nvim
```
and run `:TestMe` command that we registered in our plugin and check our log in `loggy`
we notice that the plugin process has exited.
But we carry on and run `:TestMe` one more time and to find that it fails to run again.

To confirm this I had `htop` opened with `node` filtered and I do notice that it kills the node process that the plugin started.

In order to make this work I simply removed
`console.log("should print hello");` from `child.js` and it worked just fine.

It's mentioned that `winston` is used instead of `console.log` in the readme and I wonder if that has something to do with it. 

Anyway, would be curious to find out what's causing this even though it's not a blocker for me right now.
Cheers.

**Comment by chemzqm** [comment]
`stdout` is used by rpc comunication with neovim, you should redirect it.

**Comment by shri3k** [comment]
Ahh, thanks for point that out. I did some research and looks like the following would let me use `console.log` in the child processes too.

```js
// index.js
function TestMe() {
    const child = fork(`${__dirname}/child.js`, [], {
      silent: true, //passes to the parent process instead making it available in child.stdout
    });
    child.stdout.on('data', dat => console.log(dat.toString()) );
    console.log('--end function--');
  }
```

Much appreciated. :smiley:

**Comment by justinmk** [comment]
related: https://github.com/neovim/neovim/pull/8883
