### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by CantGetRight82** [neovim/node-client#122]
There seems to be an issue when used with nodejs 12.4

Just the mention of 'Buffer' inside a plugin, triggers a 'ReferenceError: Buffer is not defined'.
When switching back to nodejs 10 the problem goes away.

**Comment by justinmk** [comment]
cannot reproduce with the steps given.

**Comment by kalekseev** [comment]
@justinmk I created a new issue with the same problem but with steps to reproduce https://github.com/neovim/node-client/issues/141
