### ISSUE TITLE
Support Volta

### ISSUE THREAD

**Issue by brainkim** [neovim/node-client#123]
[volta.sh](Volta), (formally Notion) is a node launcher which takes over global installations of npm packages. When installing "neovim" with volta I get the following error:

```
## Node.js provider (optional)
  - INFO: Node.js: v10.16.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

**Comment by mhartington** [comment]
Hey! So this would be an interesting idea. Volta does seem a bit early (even their docs state it's still in development), but could be a nice feature in the future. All that would really need to be added is an option in the node-provider of nvim.

https://github.com/neovim/neovim/blob/master/runtime/autoload/health/provider.vim


As I don't know too much about volta, it would be great if you could share some information on how to replicate the features/options that yarn/npm have in the node provider.

**Comment by billyvg** [comment]
@brainkim I believe you can install via volta by `volta install neovim`

**Comment by justinmk** [comment]
I think this was done? https://github.com/neovim/node-client/commit/5118d3525e335aa9422c40ccd1a3bcb90b5c1a13
