### ISSUE TITLE
Set default logger transport for neovim/node-client

### ISSUE THREAD

**Issue by kwonoj** [neovim/node-client#137]
![image](https://user-images.githubusercontent.com/1210596/71663168-f284d000-2d08-11ea-87fe-2f70c78ee90b.png)

It looks like neovim node client is initialized with default values (`debug` loglevel / no transport) makes all debug message keep erroring in winston.

- default loglevel may not need to be `debug`: maybe worth expose `debug` config for the extension to launch neovim in the full-debugging mode
- set default transport : to console? for debug-mode, may write it into file transport instead.

**Comment by kwonoj** [comment]
Apologies, opened issue to wrong upstream.

**Comment by vegerot** [comment]
Sorry for the bump, but how do I do this?  I can't seem to get Winston to work, and all the `BaseApi` transport methods I want are protected?  What are the public interfaces I should be using for getting buffer events and things?
