### ISSUE TITLE
Having `neovim` required will break the plugin

### ISSUE THREAD

**Issue by 3rd** [neovim/node-client#139]
Been trying to figure out why my plugin doesn't work for about two hours now.
Turns out that if there is a `require("neovim")` in the plugin it will just not work.
Importing other modules works just fine.
I couldn't find any logs related to this, is there any way to debug something like this?

Versions:
- neovim: `v0.5.0-271-g52566dd78`
- neovim node package: `"^4.7.0"`

Let me know if I can help.

Edit:
The same happens with `console.log`.
It fails with the error from this issue: https://github.com/winstonjs/winston/issues/1577

**Comment by justinmk** [comment]
There's nothing actionable here. "Doesn't work" gives us nothing to advise, we need exact error message and sample source code that produces the issue.



> The same happens with `console.log`.
> It fails with the error from this issue: [winstonjs/winston#1577](https://github.com/winstonjs/winston/issues/1577)

So it sounds like this is not related to neovim module?
