### ISSUE TITLE
types and functions are not match

### ISSUE THREAD

**Issue by imshenshen** [neovim/node-client#15]
in `generateWrappers` function , `types` are `Buffer | Window | Tabpage`, but `metadata`'s functions's type are `buffer_ | tabpage_  | ui_ | vim_`, so [this line](https://github.com/neovim/node-client/blob/master/index.js#L77) got an error.

**Comment by nhynes** [comment]
I think that this might be fixed by @14. I'll merge that now. Would you mind pulling the changes and verifying that the bug no longer exists?

**Comment by imshenshen** [comment]
is ok now, thx.
