### ISSUE TITLE
What are eval, pattern, and sync parameters for?

### ISSUE THREAD

**Issue by nomasprime** [neovim/node-client#153]
Mentioned in numerous places but I can't find any documentation on them.

**Comment by justinmk** [comment]
This example gives a hint: https://github.com/neovim/node-client/blob/00646534c5e5ae931ebf3253cbc043b7b244d8b3/examples/rplugin/node/nvim-example/index.js#L19

- `sync` forces non-async behavior
- `pattern` works like [autocmd pattern](https://neovim.io/doc/user/autocmd.html#autocmd-pattern)
- `eval` evaluates a Vimscript expression in the Nvim peer.
