### ISSUE TITLE
Cannot duck-type 'Logger' because the underlying type references hidden members

### ISSUE THREAD

**Issue by samvv** [neovim/node-client#167]
Currently, `Logger` is defined in [logger.ts](https://github.com/neovim/node-client/blob/master/packages/neovim/src/utils/logger.ts) like so:

```ts
export type Logger = Pick<winston.Logger, 'info' | 'warn' | 'error' | 'debug'>;
```

I suspect that the idea was to allow users to supply their own logging mechanism. When I try this myself, I get the following error:

```
  The types returned by 'info(...)' are incompatible between these types.
    Type 'Logger' is missing the following properties from type 'Logger': silent, format, levels, level, and 78 more.
```

That's because the methods that are picked (`info`, `warn`, etc.) are returning the inner implementation, which is the complete Winston instance and not the type represented by `Pick`.

I propose creating a new interface with methods returning `void` and defining a small wrapper around Winston that makes it compatible with that interface. It should solve my type errors, and allow others to make use of the same functionality. Something similar to the following, depending on how much logging must be made available to `neovim` internally:

```ts
export interface Logger {
  debug(message: string): void;
  verbose(message: string): void;
  info(message: string): void;
  warn(message: string): void;
  error(message: string): void;
}
```

**Comment by rhysd** [comment]
I like this idea. Since this library allows to specify user's own logger instance, `Logger` should be defined as interface.

I checked the interface defined in winston:

https://github.com/winstonjs/winston/blob/2625f60c5c85b8c4926c65e98a591f8b42e0db9a/index.d.ts#L69-L75

It seems that logging functions has some variation of arguments. So I think following loose interface for each logging functions are better to allow any logger functions to work.

```typescript
export interface Logger {
  debug(args: ...unknown[]): unknown;
  verbose(args: ...unknown[]): unknown;
  info(args: ...unknown[]): unknown;
  when(args: ...unknown[]): unknown;
  error(args: ...unknown[]): unknown;
}
````

**Comment by samvv** [comment]
Actually, digging a bit deeper I've found that it isn't that difficult to redirect output to the steam I wanted to write to using one of Winston's transports. In the end, it means adding another dependency to my `package.json` but it is acceptable for me.

Unless someone really needs this I'll close this issue in a few days.

**Comment by rhysd** [comment]
OK, let's keep current implementation.
