### ISSUE TITLE
Where does the code run

### ISSUE THREAD

**Issue by still-dreaming-1** [neovim/node-client#17]
There is sample code in the README, but it is just code. Where do you place it? I'm pretty sure it goes in a file somewhere in the rplugin directory, but is there a specific subdirectory it goes in for Node like what you do with Python? How does Neovim activate Node? Looking at the sample code, it seems to be the other way around, like the plugin starts Neovim, is that right?

**Comment by nhynes** [comment]
It goes wherever you'd like it to go! Only plugins that want to take advantage of the host have to go in an rplugin directory. When you're just using the client, you either spawn a new `nvim` instance, as is done in the demo or connect to a running instance by turning the socket at `NVIM_LISTEN_ADDRESS` into a pair of read and write streams.

If you're trying to make a plugin that offers (auto)commands and functions, you might want to check out [node-host](https://github.com/neovim/node-host/).

**Comment by still-dreaming-1** [comment]
Ah yes, node-host seems to be what I need. I just wanted to rewrite all my plugins in JavaScript and all new ones going forward in JavaScript because I prefer JavaScript over VimL. I also want the option for the plugin code to run asynchronously. I thought this was a way to do that, but it does seem node-host is a better fit. But now I'm questioning myself because I don't really understand what you mean by plugins that want to take advantage of the host. I want it to be able to anything that a VimL plugin could do as far as being able to interact with Neovim, and I want it to be asynchronous. Do you think node-host is a better fit for that?

**Comment by nhynes** [comment]
> Do you think node-host is a better fit for that?

Yes, most certainly. Basically what happens is that Neovim starts a node server that listens for commands registered by one of your plugins and asynchronously (or synchronously, if that's your bag) shuttles data back and forth.

The example project in the README should be a good starting point.

**Comment by still-dreaming-1** [comment]
Thanks! I didn't even know node-host existed.

**Comment by nhynes** [comment]
Yep! Please feel free to re-open this issue if you have any other questions.
