### ISSUE TITLE
Is there documentation for the `nvim` API?

### ISSUE THREAD

**Issue by chevex** [neovim/node-client#2]
I assume the `nvim` argument passed to the example callback in the README is a wrapper around a lower-level NeoVim API. Where can I find documentation for that API? I'd like to get in on the ground floor with this thing and start helping improve it if I can :). What resources do you think I should grok first before I would know enough to start contributing to this driver?

Nice work btw :D

**Comment by tarruda** [comment]
You can start by reading doxygen  for C files under src/nvim/api: http://neovim.io/doc/dev/files.html (except for the private dir). Most API is generated from metadata of those files.

The rules are simple:

- Functions in [vim.c](http://neovim.io/doc/dev/vim_8c.html) are added to the main Nvim object after removing the the `vim_` prefix and converting them to camelCase. For example, `vim_get_current_line` becomes `Nvim.getCurrentLine`
- [Buffer](http://neovim.io/doc/dev/api_2buffer_8c.html), [Window](http://neovim.io/doc/dev/api_2window_8c.html) and [Tabpage](http://neovim.io/doc/dev/tabpage_8c.html) have their own files. The rules are the same for vim.c, except that the methods are added to the respective class.
- All methods use node.js style callbacks(Later I will add a [fiber-wrapped]( https://github.com/laverdet/node-fibers) API)

**Comment by tarruda** [comment]
It's not documentation, but now you can refer to the automatically generated [typescript declaration file](https://github.com/neovim/node-client/blob/master/api.d.ts)
