### ISSUE TITLE
Not seeing logs from my plugin

### ISSUE THREAD

**Issue by ChristianChiarulli** [neovim/node-client#202]
I set `NVIM_NODE_LOG_FILE="$HOME/nvim_node_log"` and I see logging from the node client but not from any of the log statements in my plugin.

Example logs I'm seeing:

```
{"level":"debug","message":"getPlugin.alwaysInit"}
{"level":"debug","message":"request -> neovim.api.nvim_out_write"}
{"level":"debug","message":"response -> neovim.api.nvim_out_write: null"}
{"level":"debug","message":"host.disconnected"}
{"level":"debug","message":"host.start"}
{"level":"info","message":"handleRequest: "}
{"level":"debug","message":"request received: "}
{"level":"info","message":"handleRequest: "}
{"level":"debug","message":"host.start"}
```

I would expect to see the log statements defined in the plugin as well. To reproduce just check if the logs are working in the example bundled with this repo: https://github.com/neovim/node-client/tree/master/examples/rplugin/node/nvim-example

I'm also not sure if `ALLOW_CONSOLE` has anything to do with this but whenever I set it to `1` for instance but that doesn't seem to do anything either.

**Comment by justinmk** [comment]
> To reproduce just check if the logs are working in the example bundled with this repo: https://github.com/neovim/node-client/tree/master/examples/rplugin/node/nvim-example

? Please provide a small code sample, not an entire repo.

**Comment by justinmk** [comment]
You already are aware, but for reference, node-client seems to monkeypatch console with winston logger: https://github.com/neovim/node-client/blob/c4ba03108dbf5360d17205f43f17a717de95cfa7/README.md?plain=1#L68

I recently updated the winston dep, maybe it's worth trying again: https://github.com/neovim/node-client/commit/33e6559d032c29c13206a8cfdcb9a8f64b46ed65

> not sure if `ALLOW_CONSOLE` has anything to do with this but whenever I set it to `1` for instance but that doesn't seem to do anything either.

For reference: https://github.com/neovim/node-client/blob/c4ba03108dbf5360d17205f43f17a717de95cfa7/packages/neovim/src/utils/logger.ts#L21-L27

**Comment by ChristianChiarulli** [comment]
This is what I'm seeing now:

![image](https://github.com/neovim/node-client/assets/29136904/e32161bc-5165-41e4-86ed-275252640873)

Log:
```
ERR 2023-07-27T00:03:39.147 nvim.40391.0 chan_close_with_error:626: RPC: failed to decode msgpack
```

Code:

```javascript
module.exports = plugin => {
  plugin.setOptions({ dev: false });

  plugin.registerCommand('EchoMessage', async () => {
    try {
      console.log('EchoMessage'); // <---- this is what is causing the error
      await plugin.nvim.outWrite('Dayman (ah-ah-ah) \n');
    } catch (err) {
      console.error(err);
    }
  }, { sync: false });
};
```

Node version: v16.18.0
Neovim version: NVIM v0.10.0-dev-722+g7668f89d5
Node Client from checkhealth: 
```
Node.js provider (optional) ~
- Node.js: v16.18.0
- Nvim node.js host: /Users/chris/Library/Application Support/fnm/node-versions/v16.18.0/installation/lib/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1
```

**Comment by justinmk** [comment]
> chan_close_with_error:626: RPC: failed to decode msgpack

That sounds like something is writing to the channel, which can happen if code prints to stdout while you are using a stdio channel (as opposed to unix socket / named pipe / TCP). If `console` isn't _actually_ getting patched, I guess it would write to stdout? Can you confirm whether `console` is actually getting monkeypatched?

**Comment by justinmk** [comment]
The readme mentions: https://github.com/neovim/node-client/blob/053a222b474c21217a0d96cc8d87c44792101d9c/README.md?plain=1#L95C1-L95C99

I'm guessing this isn't working or it's happening too late.
