### ISSUE TITLE
Unknown function

### ISSUE THREAD

**Issue by nomasprime** [neovim/node-client#204]
Plugin I wrote used to work, but now I'm getting error that a node register function's no longer available.

**Comment by nomasprime** [comment]
So, the examples work, but as soon as I use a different function name, it doesn't 🤔

**Comment by justinmk** [comment]
did you run `:UpdateRemotePlugins` ?

**Comment by justinmk** [comment]
What is the function name? Casing matters: https://github.com/neovim/pynvim/issues/334

Closing since there was no reply and no repro steps.
