### ISSUE TITLE
Incorrect type definitions

### ISSUE THREAD

**Issue by samvv** [neovim/node-client#24]
Hi,

Thanks for the awesome library! However, I'm having a slight problem: some of the type definitions seem to be incorrect. For instance, with this one:

```ts
getLine(index: Buffer, cb: number): void;
```

It seems like the class type (a.k.a. `Buffer`) got prepended to the arguments list, which put everything one place to the right. Am I correct? If so, is there any chance this could be fixed? It's not a major problem, but I'm currently using the type definitions as a reference, which make finding the right args just a littlebit more difficult.

**Comment by justinmk** [comment]
Looks like https://github.com/neovim/node-client/commit/c9725b34ce15a045f0bbffa975a3aa524b727684 changed that. @billyvg @nhynes @rhysd does that seem right?

**Comment by rhysd** [comment]
I found some mistakes so I created PR. Could you review it?

@justinmk 

`nvim_set_current_win` looks not working on nvim 0.2.0. Was it changed in 0.2.0?

@samvv 

Could you confirm the PR change works for you?

**Comment by samvv** [comment]
@rhysd Looks good to me (y)

**Comment by billyvg** [comment]
Closed for #28
