### ISSUE TITLE
Deadlock when registering plugin host

### ISSUE THREAD

**Issue by nhynes** [neovim/node-client#3]
While trying to implement a plugin host, I ran into difficulties with deadlock. The crux of the issue is that this library waits until *after* receiving api info to register the `request` and `notification` handlers. This prevents it from handling Neovim's synchronous `specs` request (@see [the request](https://github.com/neovim/neovim/blob/master/runtime/autoload/remote/host.vim#L142) and  how it [blocks](https://github.com/neovim/neovim/blob/master/src/nvim/eval.c#L12861)).

```
Neovim              Node
specs -------------> *       (blocking request on Neovim's end)
  * <------------ api_info   (blocking request on Node's end)
```

I see two solutions to this problem (though I may be myopic!). The first is to immediately register the `request` and `notification` handlers and return a *promise* on the fully-populated nvim object (and convert the rest of the library to use promises, too). The second, which seems like the simplest way to avoid duplication of effort for clients, is to allow Neovim, acting as a RPC client, to handle requests on a separate thread, like a RPC server.

It goes without saying that I'd be happy to help look into whichever solution is deemed most appropriate.

Edit: a third solution would be to simply buffer non-specs requests/notifications until the api has been processed.

**Comment by tarruda** [comment]
I'm already working on a branch where Neovim runs libuv event loop in a separate thread and the second solution would come naturally, but if you don't feel like waiting(I may open a PR in Neovim main repo today, but it may take at least a week for it to be merged), I wouldn't mind a PR to this repo that implements the buffering of requests/notifications.

**Comment by nhynes** [comment]
Fantastic! I'll hold off until then.
Once that happens, though, do you think it reasonable to add to this repository a few files that would handle plugin hosting? They could go in a new repo, but it'd be convenient to have this repo contain the required .vim files and, in JS land, export both NvimClient (i.e. `attach`) and NvimHost.

**Comment by tarruda** [comment]
> Once that happens, though, do you think it reasonable to add to this repository a few files that would handle plugin hosting?

I was thinking about following the "micro module" approach that's so common on node.js world and have the host go into a separate repository, as it would be perfectly fine to have a program use the client but not the host library, though that is only a matter of aesthetics.

>  but it'd be convenient to have this repo contain the required .vim files and, in JS land, export both NvimClient (i.e. attach) and NvimHost.

Agreed. It would also be cool if the vim plugin had an option to automatically install node.js to a private location, freeing the user from the burden of setting up a node.js installation himself. I was thinking of implementing this approach myself for the python client/host, driven by the great amount of users that have trouble setting up the host for Neovim python plugins.

If you are interesting in maintaining the node.js/neovim code, I can create a repo in the org and add you as a maintainer.

**Comment by nhynes** [comment]
> I was thinking about following the "micro module" approach that's so common on node.js world and have the host go into a separate repository

This is a good point. My main concern there was visibility, but if it were a repo in the org (or the package manager had a great indexing service), then this wouldn't be an issue. I suppose that I'd envisioned a diverse ecosystem of [sometimes competing] plugin hosts and clients to be picked and chosen from by the user.

> If you are interesting in maintaining the node.js/neovim code, I can create a repo in the org and add you as a maintainer.

I'd be happy to maintain any Node code if it'll help you and the other core devs focus on the bigger picture.

> It would also be cool if the vim plugin had an option to automatically install node.js to a private location, freeing the user from the burden of setting up a node.js installation himself

While I think that managing private copies of runtimes might get out of hand very quickly, if you're going to go with this approach I'd like to suggest storing each in a location that's shared with each host to prevent duplication (as opposed to NPM-style recursive dependencies). I do agree that the out-of-the-box experience needs to be as streamlined as possible, though. I'll think about it some more and see if I can offer a sufficiently general solution.

**Comment by tarruda** [comment]
Done. Created [node-host](https://github.com/neovim/node-host) so you can push code to it when you have something working.

**Comment by tarruda** [comment]
@nhynes can you verify if the deadlock still happens on latest master?

**Comment by nhynes** [comment]
@tarruda I just checked using the masters on neovim, node-client, and node-host and have confirmed that deadlock continues to be resolved.

I just remembered that npm requires an explicit publish step. Would you mind publishing 1.0.5 so that it can be consumed by node-host?
