### ISSUE TITLE
bug: Transport.attach throws an unhandled TypeError

### ISSUE THREAD

**Issue by andrewDoing** [neovim/node-client#403]
I'm not actually sure whether this is intended or not, but an exception is thrown and otherwise unhandled in transport.ts

https://github.com/neovim/node-client/blob/65ddb5e7c8fa6c1bd4a6cd6564ad0cdf83b7e92c/packages/neovim/src/utils/transport.ts#L114

If this is intended, perhaps I can get some guidance on fixing this issue in the vscode-neovim extension:

https://github.com/vscode-neovim/vscode-neovim/issues/2184

**Comment by justinmk** [comment]
Did you narrow down the issue? I would guess it's not a bug in node-client, but perhaps this error could try to print (part of) the unexpected value, to help with troubleshooting.

**Comment by andrewDoing** [comment]
I could PR the debugging logs I added, that's a good idea. I assume it's not a bug in the node client but I'm not 100% sure. 

I wasn't able to trace the source of the data coming in from vscode-neovim, or why it's not an array. Something in the visible window syncing code sends data to the node client which either is wrong when sent or corrupted. 

The behavior is reproduced by using Copilot Chat to generate code, or by scrolling through previously generated code.

**Comment by justinmk** [comment]
> I could PR the debugging logs I added

did you add those to node-client? I think it would help a lot if the `throw new TypeError...` you mentioned here tried to include a useful string representation of the invalid value. PR welcome for that

**Comment by justinmk** [comment]
See https://github.com/neovim/node-client/pull/404
