### ISSUE TITLE
Move plugin decorators to a separate package

### ISSUE THREAD

**Issue by billyvg** [neovim/node-client#42]
Should be moved into a separate package since plugin developers do not need the entire API client.

**Comment by mhartington** [comment]
@billyvg hey again! 

I've been using the decorators again, so will to pick this up and work it.

**Comment by billyvg** [comment]
@mhartington I'm reconsidering if we should split this up, and if so, I think we'd want to keep a mono-repo and use `lerna`, to make things easier to maintain. Thoughts?

**Comment by mhartington** [comment]
Sounds like a good idea to me.

**Comment by mhartington** [comment]
A bit delayed, but initial work is here.

https://github.com/neovim/node-client/tree/lerna-port

Will need to go through and verify packages being installed, and commands we'll want setup.
Also though is packages. All the "cool kids" these days use scoped packages, maybe this should too? 

```
@neovim/core
@neovim/decorators
```

**Comment by billyvg** [comment]
@mhartington let's keep the core package the same for now, but use scoped packages for any new packages.

**Comment by billyvg** [comment]
Closed in #116 🎉
