### ISSUE TITLE
Can not register any command or function using plugin API

### ISSUE THREAD

**Issue by chemzqm** [neovim/node-client#53]
I'm using the example plugin code from readme, I can have plugin registered but no luck for command and function, the result in generated `rplugin.vim` would be
``` vim
" node plugins
call remote#host#RegisterPlugin('node', '/Users/chemzqm/.vim/rplugin/node/index.js', [
     \ ])
```

The result of `CheckHealth`:
```
## Node provider (optional)
  - INFO: Node: v9.7.1
  - INFO: Host: /usr/local/bin/neovim-node-host
  - OK: Latest "neovim" npm is installed: 3.5.2
```

I have the same issue for neovim 0.2.2 and latest master branch.

**Comment by chemzqm** [comment]
Find the reason, the code should be transformed.

**Comment by justinmk** [comment]
@chemzqm Can you give example before/after code in case it helps others?

**Comment by chemzqm** [comment]
The module `babel-plugin-transform-es2015-modules-commonjs` should be used for transform the code, the code like:
```
import { Plugin, Function, Autocmd, Command } from 'neovim'
```
would be transformed to:
```
var _neovim = require('neovim');
....
```
It fails with untransformed code, but it could only be observed by `NVIM_NODE_LOG_FILE `, it would be valuable if the failure could be detected by `UpdateRemotePlugins` command

**Comment by billyvg** [comment]
Yeah sorry, this is still on my todo: https://github.com/neovim/node-client/issues/43
