### ISSUE TITLE
Neovim npm package not loaded properly

### ISSUE THREAD

**Issue by nbardy** [neovim/node-client#55]
Running `:UpdateRemotePlugins` gives and error
```
function remote#host#UpdateRemotePlugins[6]..<SNR>72_RegistrationCommands[15]..remote#
host#Require[10]..provider#node#Require, line 2
Vim(echoerr):Cannot find the "neovim" node package. Try :checkhealth
```
`npm install -g neovim` runs fine, but I still get the same error.

Relevant :checkhealth
```
## Node.js provider (optional)
  - INFO: Node.js: v9.8.0
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?
```

**Comment by justinmk** [comment]
So what does `npm install -g neovim` say if you run it in a shell, as the advice mentions?

**Comment by nbardy** [comment]
Hmm. looking into it more it appears to be an npm problem.
`npm install -g neovim` reports successful update. But the package isn't actually updating on the system.
