### ISSUE TITLE
Completion on command

### ISSUE THREAD

**Issue by SevereOverfl0w** [neovim/node-client#65]
I can't see in the API how to set completion for a command when registering it.

**Comment by mhartington** [comment]
@SevereOverfl0w Hi there! Are you authoring the plugin in typescript? Do you have an example I could inspect? I have type information being provided in my plugin setup. 
![node-client-types](https://user-images.githubusercontent.com/2835826/39973338-93e52d4a-56ec-11e8-964d-e3dd12534988.gif)

**Comment by chemzqm** [comment]
As far as I know, the `-complete` option is not implemented.

**Comment by SevereOverfl0w** [comment]
The previous version of the plugin I updated had complete set to file for a particular command. I assume it worked at some point. 

Is complete not implemented on node or the Neovim side? 

On May 14, 2018 2:26:11 AM GMT+01:00, Qiming zhao <notifications@github.com> wrote:
>As far as I know, the `-complete` option is not implemented.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/neovim/node-client/issues/65#issuecomment-388672380

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chemzqm** [comment]
node-client only have these fields for command:
```
export interface CommandOptions {
  sync?: boolean;
  range?: string;
  nargs?: string;
}
```

**Comment by mhartington** [comment]
Ahh, sorry, I was misunderstanding the issue. Yes, I don't think this is currently supported, but it looks like this is supported in the python plugin, so we should probably add it. I'll take a look!
