### ISSUE TITLE
`generateApi` not using the result from `nvim_get_api_info`?

### ISSUE THREAD

**Issue by chemzqm** [neovim/node-client#76]
I want to try out https://github.com/neovim/neovim/pull/7917, it introduce some new API, like `nvim_buf_attach`,  but it doesn't exists on buffer object, so how could I make use of it?

**Comment by justinmk** [comment]
@chemzqm You can always call RPC methods via `request()`, e.g.

    request('nvim_buf_attach', 1, {})

**Comment by billyvg** [comment]
Yeah we made a decision to have a hard coded API, instead of dynamically generating a node.js API via neovim. In the future it would be great to automate detecting new APIs.
